### PR TITLE
Added Protect integration create

### PR DESCRIPTION
**Pull request by danjamf**
# Change

Added Create for Protect Integration using same struct format as API docs

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

### CODE REVIEW

**Comment by ShocOne** [comment]
The data model suggests the resp is

{
  "id": "1",
  "apiClientId": "esgzYzYBqN7wCImwyusbQcXob2qalGMN",
  "apiClientName": "Jamf Pro integration",
  "registrationId": "6f250316-2cfb-4521-8cb7-bfaf46497bc5",
  "protectUrl": "https://examplejamfprotect.jamfcloud.com/graphql",
  "lastSyncTime": "2003-01-05T18:00:14.885Z",
  "syncStatus": "COMPLETED",
  "autoInstall": true
}

rather than using this

type ResourceJamfProtectIntegrationCreateSettings struct {
	ProtectURL string `json:"protectUrl"`
	ClientID   string `json:"clientId"`
	Password   string `json:"password"`
}

so it will need a refined struct for the response handling

**Comment by danjamf** [comment]
The response struct from `CreateJamfProtectIntegration` is also using `ResourceJamfProtectIntegrationSettings` and not the newly added `ResourceJamfProtectIntegrationCreateSettings`

**Comment by danjamf** [comment]
To add, I have testing Create and Delete (using the existing func) and working as expected

**Comment by ShocOne** [comment]
@danjamf please see PR #449 - thanks

**Pull request closed without merging**
